name: Jesse Hamble
favicon: null
layout_spectrum: 0.06107688252814114
typography_spectrum: 0.2362968570087105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.18755055335350335
  lightness: 0.5153537085279822
  saturation: 0.8182539981789887
  rhythmicContrast: 0.2354907540138811
purpose: []
